version: "3.9"
services:
  web:
    container_name: auth
    image: authbe2:latest
    restart: always
    build: .
    ports:
      - '4000:4000'
    environment:
      MONGO_DB_URI: mongodb://natsinee:natsineedev@mongo/test?authSource=admin
    env_file:
      - .env
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo:latest
    volumes:
      - ./data:/data/db
    ports:
      - '47019:47019'
    environment:
      MONGO_INITDB_ROOT_USERNAME: natsinee
      MONGO_INITDB_ROOT_PASSWORD: natsineedev
      MONGO_INITDB_DATABASE: test
    env_file:
      - .env